[package]
name = "rusty-uevr"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-uevr-macros = { path = "./macros" }
windows = { version = "0.58.0", features = [
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Direct3D12",
  "Win32_UI_Input_XboxController",
] }
